Add dao-9 solution
AndreiYazadzhi/dao-3-homework pull request #10
Opened 2021-01-23 17:27 UTC by AndreiYazadzhi

2021-01-24 06:10 UTC, NikolayFatkullin approved these changes

2021-01-25 17:43 UTC, RomanDubovskyi requested changes
nice, almost there

2021-01-25 17:43 UTC, RomanDubovskyi commented on src/main/java/com/dao/homework/dao/jdbc/CarDaoJdbcImpl.java
> +        String password = resultSet.getObject("password", String.class);
ideally, we don't want to expose users' password when passing an object to a front end

2021-01-25 17:43 UTC, RomanDubovskyi commented on src/main/java/com/dao/homework/security/AuthenticationServiceImpl.java
> +                && driverFromDb.get().getLogin().equals(login)) {
```suggestion
                ) {
```
that will be checked in findByLogin, if login is incorrect the check will fail on the first condition

2021-01-25 17:43 UTC, RomanDubovskyi commented on src/main/java/com/dao/homework/web/filters/AuthenticationFilter.java
> +        if (driverId == null || driverService.get(driverId) == null) {
can the service return null?

2021-01-26 08:36 UTC, RomanDubovskyi requested changes

2021-01-26 08:36 UTC, RomanDubovskyi commented on src/main/java/com/dao/homework/web/filters/AuthenticationFilter.java
> +            .getInstance(DriverService.class);
do we use it here?

2021-01-26 08:36 UTC, RomanDubovskyi commented on src/main/java/com/dao/homework/web/filters/AuthenticationFilter.java
> +    public static final Set<String> test = new HashSet<>();
what does "test" mean?

2021-01-26 09:31 UTC, RomanDubovskyi approved these changes

2021-01-26 14:00 UTC, merged