Add dao 8 solution
AndreiYazadzhi/dao-3-homework pull request #9
Opened 2021-01-20 20:20 UTC by AndreiYazadzhi

2021-01-21 11:12 UTC, IwalkInSilence approved these changes

2021-01-21 13:37 UTC, dmytro-hryhoruk requested changes
let's create directory for each jsp entity
car/all.jsp
car/add.jsp
driver/add.jsp 
and so on..

2021-01-21 13:37 UTC, dmytro-hryhoruk commented on src/main/java/com/dao/homework/controllers/CreateCarController.java
> +        Long manufacturerId = Long.valueOf(request.getParameter("manufacturerId"));
```suggestion
        Long manufacturerId = Long.valueOf(request.getParameter("manufacturer_Id"));
```

2021-01-21 13:37 UTC, dmytro-hryhoruk commented on src/main/java/com/dao/homework/controllers/CreateDriverController.java
> +        String driverLicense = String.valueOf(request.getParameter("licenseNumber"));
```suggestion
        String driverLicense = request.getParameter("license_number");
```
change it everywhere

2021-01-21 13:37 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/driver/add</url-pattern>
```suggestion
        <url-pattern>/drivers/add</url-pattern>
```

2021-01-21 13:37 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +
```suggestion
```

2021-01-21 13:37 UTC, dmytro-hryhoruk commented on src/main/webapp/web.xml
> +        <url-pattern>/drivers/add</url-pattern>
```suggestion
        <url-pattern>/cars/drivers/add</url-pattern>
```

2021-01-22 09:44 UTC, dmytro-hryhoruk approved these changes
for packages name(jsp packages too) user singular form,
for ur - patterns use plural:
views/car/add.jsp
but the url to controller would be /cars/add

2021-01-22 10:25 UTC, merged